export type Doctor = {
  id: string;
  referCode: string; // Unique reference ID generated by backend
  name: string;
  email: string;
  phone: string;
  specialization: string;
  qualification: string;
  registrationNumber: string;
  hospital?: string;
  address?: string;
  city?: string;
  state?: string;
  pincode?: string;
  commissionRate: number; // Percentage
  commissionType: "percentage" | "fixed";
  fixedAmount?: number; // If commission type is fixed
  totalReferrals?: number;
  totalCommissionEarned?: number;
  isActive?: boolean;
  joinedDate?: string;
  lastReferralDate?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type DoctorFormData = Omit<
  Doctor,
  "id" | "referCode" | "totalReferrals" | "totalCommissionEarned" | "lastReferralDate" | "createdAt" | "updatedAt"
>;

export type CommissionLog = {
  id: string;
  doctorId: string;
  doctorName: string;
  referCode: string;
  orderId: string;
  patientName: string;
  orderAmount: number;
  commissionAmount: number;
  commissionRate: number;
  date: string;
  status: "pending" | "paid" | "cancelled";
};
