import type { Metadata } from "next";
import "../globals.css";
import SvgDefs2 from "@/components/custom/pages/SvgDefs2";
import CTA from "@/components/custom/pages/CTA";
import Footer from "@/components/custom/pages/Footer";
import { ektaLogo } from "@/assets/images.export";
import {
  footerColumns,
  socialLinks,
} from "@/components/custom/pages/Data.pages";
import Navbar from "@/components/custom/pages/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Navbar />
      <SvgDefs2 />
      {children}
      <CTA />
      <Footer
        logo={ektaLogo}
        columns={footerColumns}
        socials={socialLinks}
        copyright={
          "© 2025 Ektajanchkendra. All rights reserved. | Privacy Policy | Terms of Service"
        }
      />
    </section>
  );
}
